name: ci

on:
  push:
    paths:
    - "**.py"
    - .github/workflows/ci.yml

jobs:

  ci:
    timeout-minutes: 15
    continue-on-error: ${{ matrix.experimental }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        os: [ubuntu-latest]
        experimental: [true]
        include:
        - os: windows-latest
          python-version: "3.12"
          experimental: false
        - os: macos-latest
          python-version: "3.12"
          experimental: false

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - run: pip install .[tests,lint,io]

    - name: syntax check
      timeout-minutes: 1
      if: runner.os == 'Linux'
      run: flake8

    - name: type annotation check
      timeout-minutes: 10
      if: runner.os == 'Linux'
      run: mypy --install-types --non-interactive

    - run: pytest
      timeout-minutes: 7
